grails-app/domain/emsi/mbds/Annonce.groovy
package emsi.mbds

class Annonce {

    String title
    String description
    Float price
    String ref
    Boolean status = Boolean.FALSE

    Date dateCreated
    Date lastUpdated

    List illustrations

    static hasMany = [illustrations: Illustration]

    static belongsTo = [author: User]

    static constraints = {
        title nullable: false, blank: false, size: 3..55
        description nullable: false, blank: false
        price nullable: true, scale: 2, min: 0F
        ref nullable: false, blank: false, unique: true
        status nullable: false
    }

    static mapping = {
        description type: 'text'
    }
}

grails-app/controllers/emsi/mbds/AnnonceController.groovy
package emsi.mbds

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*


@Secured(['ROLE_ADMIN','ROLE_MODO'])
class AnnonceController {

    AnnonceService annonceService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    @Secured(['ROLE_CLIENT','ROLE_ADMIN','ROLE_MODO'])
    def index(Integer max, String mot) {
        //params.max = Math.min(max ?: 10, 100)
        System.out.println("-------------------------------------------")
        System.out.println(mot)
        System.out.println("-------------------------------------------")
        if(mot!=null){
            def l = annonceService.list()
            def l2 = new ArrayList<Annonce>()
            for (i in annonceService.list(params)){
                if(i.title.toLowerCase().contains(mot.toLowerCase())){
                    l2.add(i)
                    System.out.println("added")
                }
            }
            System.out.println(l2.toString())
            System.out.println("-------------------------------------------")
            System.out.println(l2.size())
            System.out.println("-------------------------------------------")
            respond l2, model:[annonceCount: l2.size()]
            return
        }
        params.max = Math.min(max ?: 10, 100)
        System.out.println(annonceService.list(params))
        System.out.println(annonceService.count())
        //respond annonceService.list(params), model:[annonceCount: annonceService.count()]
        respond annonceService.list(params), model:[annonceCount: annonceService.count()]
    }
    @Secured(['ROLE_CLIENT','ROLE_ADMIN','ROLE_MODO'])
    def show(Long id) {
        respond annonceService.get(id)
    }

    def create() {
        respond new Annonce(params)
    }

    def save(Annonce annonce) {
        if (annonce == null) {
            notFound()
            return
        }

        try {
            def a = annonce.getId()
            def b = annonce.getAuthor().getUsername()
            annonce.setRef("#" + a + ":" +b)
            def ann = annonceService.save(annonce)
            def aa = ann.getId()
            def bb = ann.getAuthor().getUsername()
            ann.setRef("#" + aa + ":" +bb)
            ann = annonceService.save(ann)

            def f = request.getFile('filename')
            if (f.empty) {
                System.out.println("file cannot be empty")
                flash.message = 'file cannot be empty'
                redirect action: 'create'
                return
            }


            String nomDeFichier = UUID.randomUUID().toString() + '.png'

            def file = new File(grailsApplication.config.exams_mbds.illustrations.path + nomDeFichier)
            System.out.println(grailsApplication.config.exams_mbds)
            System.out.println(grailsApplication.config.getProperty('exams_mbds'))

            while (file.exists()) {
                nomDeFichier = UUID.randomUUID().toString() + '.png';
                file = new File(grailsApplication.config.exams_mbds.illustrations.path + nomDeFichier)
            }
            System.out.println(nomDeFichier)
            f.transferTo(file)


            def illustrationInstance = new Illustration(filename: nomDeFichier)


            ann.addToIllustrations(illustrationInstance)


            annonceService.save(ann)
        } catch (ValidationException e) {
            respond annonce.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*' { respond annonce, [status: CREATED] }
        }
    }
    @Secured(['ROLE_CLIENT','ROLE_ADMIN','ROLE_MODO'])
    def edit(Long id) {
        respond annonceService.get(id)
    }
    @Secured(['ROLE_CLIENT','ROLE_ADMIN','ROLE_MODO'])
    def update(Annonce annonce) {
        if (annonce == null) {
            notFound()
            return
        }

        try {
            def f = request.getFile('filename')
            if (f.empty) {
                System.out.println("file cannot be empty")
                flash.message = 'file cannot be empty'
                redirect action: 'create'
                return
            }
            String nomDeFichier = UUID.randomUUID().toString() + '.png'

            def file = new File(grailsApplication.config.exams_mbds.illustrations.path + nomDeFichier)
            System.out.println(grailsApplication.config.exams_mbds)
            System.out.println(grailsApplication.config.getProperty('exams_mbds'))

            while (file.exists()) {
                nomDeFichier = UUID.randomUUID().toString() + '.png';
                file = new File(grailsApplication.config.exams_mbds.illustrations.path + nomDeFichier)
            }
            System.out.println(nomDeFichier)
            f.transferTo(file)


            def illustrationInstance = new Illustration(filename: nomDeFichier)


            ann.addToIllustrations(illustrationInstance)


            annonceService.save(ann)
        } catch (ValidationException e) {
            respond annonce.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*'{ respond annonce, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        annonceService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'annonce.label', default: 'Annonce'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'annonce.label', default: 'Annonce'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/annonce/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-annonce" class="content scaffold-create px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.annonce}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.annonce}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <!--<g:form resource="${this.annonce}" method="POST"> -->
                <form enctype="multipart/form-data" action="/annonce/save" method="post">
                <fieldset class="form">
                    <table class="table">
                        <tbody>
                        <tr>
                            <td style="font-size: medium;"> <label for="title" class="inline-flex items-center text-gray-600 dark:text-gray-400">Titre :</label> </td>
                            <td><input name="title" type="text" class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input" id="title" placeholder=""></td>
                        </tr>
                        <tr>
                            <td style="font-size: medium;"> <label for="description" class="inline-flex items-center text-gray-600 dark:text-gray-400">Description :</label></td>
                            <td> <input name="description" type="text" class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input" id="description" placeholder=""></td>
                        </tr>

                        <tr>
                            <td style="font-size: medium;"> <label for="price" class="inline-flex items-center text-gray-600 dark:text-gray-400">Prix :</label> </td>
                            <td> <input name="price" type="text"  class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input" id="price" placeholder=""></td>
                        </tr>
                        <tr style="display: none">
                            <td style="font-size: medium;"> <label for="ref" class="inline-flex items-center text-gray-600 dark:text-gray-400">Ref :</label> </td>
                            <td> <input name="ref" type="text" disabled class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input" id="ref" value="reference" ></td>

                        </tr>
                        <tr>
                            <sec:ifAnyGranted roles="ROLE_ADMIN">
                                <g:link controller="saleAd">
                                    <td style="font-size: medium;"> <label for="author" class="inline-flex items-center text-gray-600 dark:text-gray-400">Auteur:</label> </td>
                                    <td><g:select class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input" name="author" from="${emsi.mbds.User.list()}" optionKey="id" optionValue="username"/></td>
                                </g:link>
                            </sec:ifAnyGranted>



                        </tr>
                        <tr>
                            <td> <input name="filename" type="file" class="custom-file-input" id="customFile"></td>
                            <td><img src="${grailsApplication.config.exams_mbds.illustrations.url}/${filename}"/></td>
                        </tr>
                        </tbody>
                    </table>




                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="Créer"/>
                </fieldset>
                </form>
            <!--</g:form>-->
        </div>
    </body>
</html>

grails-app/views/annonce/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="" role="navigation">
            <div style="margin-top:10px" role="navigation">
                <ul>
                    <li><button class="px-3 py-1 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-md active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"><g:link class="" action="index">Back</g:link></button></li>

                </ul>
            </div>
        </div>
        <div id="edit-annonce" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.annonce}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.annonce}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.annonce}" enctype="multipart/form-data" method="POST" >
                <g:hiddenField name="version" value="${this.annonce?.version}"/>
            <!--   <form enctype="multipart/form-data" action="/annonce/update" method="PUT">-->
               <fieldset class="form">
                   <table class="table">
                       <tr>
                           <td style="font-size: medium;"><label for="title" class="inline-flex items-center text-gray-600 dark:text-gray-400">Titre :</label></td>
                           <td><input name="title" type="text" class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input" id="title" value="${annonce.title}"></td>
                        </tr>
                        <tr>
                            <td style="font-size: medium;"><label for="description" class="inline-flex items-center text-gray-600 dark:text-gray-400">Description :</label></td>
                            <td><input name="description" type="text" class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input" id="description"
                                       value="${annonce.description}"></td>
                        </tr>
                        <tr>
                            <td style="font-size: medium;"><label for="price" class="inline-flex items-center text-gray-600 dark:text-gray-400">Prix :</label></td>
                            <td><input name="price" type="text" class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input" id="price"
                             value="<g:formatNumber number="${annonce.price}" type="number" maxFractionDigits="4" />"></td>
                        </tr>
                        <tr><sec:ifAnyGranted roles="ROLE_ADMIN">
                            <td style="font-size: medium;"><label for="author" class="inline-flex items-center text-gray-600 dark:text-gray-400">Auteur:</label></td>

                            <td><g:select name="author" from="${emsi.mbds.User.list()}" optionKey="id" class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"
                                          optionValue="username"/></td>
                        </sec:ifAnyGranted>
                            <sec:ifAnyGranted roles="ROLE_CLIENT">
                                <td style="font-size: medium;"><label for="author" class="inline-flex items-center text-gray-600 dark:text-gray-400">Auteur:</label></td>

                                <td><input disabled name="author" type="text" class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input" id="author"
                                           value="${annonce.author.username}">
                                </td>
                            </sec:ifAnyGranted>

                        </tr>
                        %{--}<tr>
                            <td style="font-size: medium;"><label for="price">Image(s) sélectionnées :</label></td>
                            <td><g:each in="${saleAd.illustrations}" var="image">
                                <img style="height: 100px;"
                                     src="${grailsApplication.config.projet1_test.illustrations.url}${image.filename}"
                                     alt="Images"/>
                            </g:each></td>
                        </tr>--}%
                    </table>
                    <table class="table borderless">
                        <tr>
                            <td style="font-size: medium;"><label for="customFile" class="inline-flex items-center text-gray-600 dark:text-gray-400">Choisir une image :</label></td>
                            <td><input name="filename" type="file" class="custom-file-input" id="customFile"></td>
                        </tr>
                    </table>

                </fieldset>

                <div class="">
                    <input class="px-10 py-4 font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" type="submit" value="Update"/>
                </div>
                <!--</form>-->
            </g:form>
        </div>
    </body>
</html>

grails-app/views/annonce/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
        <style>
            a{

            }
        </style>
    </head>
    <body>
        <a href="#list-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
    <!--
    <div class="" >
        <ul>
            <li>
                <button class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
                    <a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a>
                </button>
            </li>
            <li>
                <button class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
                    <g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link>
                </button>
            </li>
        </ul>
    </div> -->

    <div id="list-annonce" class="content scaffold-list" role="main" style="display:inline-block">
        <h1><g:message code="default.list.label" args="[entityName]" /></h1>
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>

        <div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
            <div class="w-full overflow-x-auto">
                <table class="w-full whitespace-no-wrap">
            <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
            <th class="px-3 py-2">title</th>
            <th class="px-3 py-2">Description</th>
            <th class="px-3 py-2">Price</th>
            <th class="px-3 py-2"> Reference</th>
            <th class="px-3 py-2">status</th>
            <th class="px-3 py-2">Illustrations</th>
            <th class="px-3 py-2">Author</th>
                <th class="px-3 py-2">Edit</th>
                <th class="px-3 py-2">Show</th>
                <th class="px-3 py-2">Delete</th>
            </tr>
                    <tbody
                            class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800"
                    >
            <g:each in="${annonceList}">
                <tr class="text-gray-700 dark:text-gray-400">
                    <td class="px-3 py-2">${it.title}</td>
                    <td class="px-3 py-2">${it.description}</td>
                    <td class="px-3 py-2">${it.price}</td>
                    <td class="px-3 py-2">${it.ref}</td>
                    <td class="px-3 py-2">${it.status}</td>
                    <td class="px-3 py-2">
                        <g:each in="${it.illustrations}" var="image">
                            <img style="height: 100px;" src="${grailsApplication.config.exams_mbds.illustrations.url}${image.filename}" alt="Images" />
                        </g:each>

                    </td>
                    <td class="px-3 py-2">${it.author.username}</td>
                    <td class="px-3 py-2">
                        <g:if test="${it.author.username.equals(sec.loggedInUserInfo(field: 'username').toString()) || sec.loggedInUserInfo(field: 'username') == 'admin' || sec.loggedInUserInfo(field: 'username') == 'modo'}">
                            <g:link controller='annonce' action='edit' id='${it.id}'                                                  class="btn btn-success">
                            <span class="fa fa-pencil"></span></g:link>


                        </g:if>
                    </td>
                    <td class="px-3 py-2"><g:link controller='annonce' action='show' id='${it.id}'
                                                  class="btn btn-primary"><span class="fa fa-eye"></span></g:link></td>
                    <td class="px-3 py-2">
                        <sec:ifLoggedIn>
                            <sec:ifAnyGranted roles="ROLE_ADMIN">
                        <g:form resource="${it}" method="DELETE">
                            <button class="btn btn-danger" type="submit"
                                    onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Êtes-vous sur ?')}');">
                                <span class="fa fa-trash"></span>
                            </button>
                        </g:form>
                            </sec:ifAnyGranted>
                        </sec:ifLoggedIn>

                    </td>
                </tr>
            </g:each>
                    </tbody>
        </table>
            </div>
        </div>


    </div>
        <div class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800 flex col-span-4 mt-2 sm:mt-auto sm:justify-end ">
            <g:paginate total="${annonceCount ?: 0}" />
        </div>

    </body>
</html>