grails-app/domain/emsi/mbds/User.groovy
package emsi.mbds

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

    private static final long serialVersionUID = 1

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    static hasMany = [annonces: Annonce]

    Set<Role> getAuthorities() {
        (UserRole.findAllByUser(this) as List<UserRole>)*.role as Set<Role>
    }

    static constraints = {
        password nullable: false, blank: false, password: true
        username nullable: false, blank: false, unique: true
    }

    static mapping = {
	    password column: '`password`'
    }
}

grails-app/controllers/emsi/mbds/UserController.groovy
package emsi.mbds

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*


@Secured(['ROLE_ADMIN','ROLE_MODO'])
class UserController {

    UserService userService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond userService.list(params), model:[userCount: userService.count()]
    }
    @Secured(['ROLE_CLIENT','ROLE_ADMIN','ROLE_MODO'])
    def show(Long id) {
        respond userService.get(id)
    }

    def create() {
        respond new User(params)
    }

    def save(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond userService.get(id)
    }

    def update(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*'{ respond user, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        userService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>

        <div id="create-user" class="content scaffold-create px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800" role="main">
            <h1>In this section you can add a new user</h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.user}" method="POST">
                <!--<fieldset class="form">
                    <f:all bean="user"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>-->


                    <div class="form-group required">
                        <label for="username">Username
                            <span class=""></span>
                        </label><input class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input" type="text" name="username" value="" r
                                       id="username">
                    </div>

                    <div class="form-group ">
                        <label for="password">Password
                            <span class=""></span>
                        </label><input class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input" type="password" name="password"  value=""
                                       id="password">
                    </div>


                <div class="form-group">
                    <label for="role">Rôle
                        <span class="required-indicator">*</span>
                    </label>
                    <g:select class="form-control" from="${emsi.mbds.Role.list()}"
                              name="role" optionKey="id" optionValue="authority"/>
                </div>

                <g:submitButton class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" name="create"
                                value="${message(code: 'default.button.create.label', default: 'Create')}"/>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/user/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
    <div class="" role="navigation">
        <div style="margin-top:10px" role="navigation">
            <ul>
                <li><button class="px-3 py-1 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-md active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"><g:link class="" action="index">Back</g:link></button></li>

            </ul>
        </div>
    </div>
        <div id="edit-user" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>


            <g:form resource="${this.user}" method="PUT">
                <g:hiddenField name="version" value="${this.user?.version}" />

                <div class="form-group required">
                    <label for="username">Username
                        <span class=""></span>
                    </label><input class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input" type="text" name="username"  r
                                   id="username" value="${user.username}">
                </div>

                <div class="form-group ">
                    <label for="password">Password
                        <span class=""></span>
                    </label><input class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input" type="password" name="password"  value=""
                                   id="password">
                </div>

                <div class="form-group ">
                    <label for="accountExpired">Account Expired
                        <span class=""></span>
                    </label>
                    <g:checkBox id="accountExpired" name="accountExpired" value="${user.accountExpired}" class="text-purple-600 form-checkbox focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray" />
                </div>
                <div class="form-group ">
                    <label for="accountLocked">Account Locked
                        <span class=""></span>
                    </label>
                    <g:checkBox id="accountLocked" name="accountLocked" value="${user.accountLocked}" class="text-purple-600 form-checkbox focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray" />
                </div>
                <div class="form-group ">
                    <label for="passwordExpired">Password Expired
                        <span class=""></span>
                    </label>
                    <g:checkBox id="passwordExpired" name="passwordExpired" value="${user.passwordExpired}" class="text-purple-600 form-checkbox focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray" />
                </div>
                <div class="form-group ">
                    <label for="enabled">Enabled
                        <span class=""></span>
                    </label>
                    <g:checkBox id="enabled" name="enabled" value="${user.enabled}" class="text-purple-600 form-checkbox focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray" />
                </div>
                <div class="form-group">
                    <label for="role">Rôle
                        <span class="required-indicator">*</span>
                    </label>
                    <g:select class="form-control" from="${emsi.mbds.Role.list()}"
                              name="role" optionKey="id" optionValue="authority"  />
                </div>
                <div class="">
                    <input class="px-10 py-4 font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" type="submit" value="Update"/>
                </div>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/user/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

        <div id="list-user" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
                <div class="w-full overflow-x-auto">
                    <table class="w-full whitespace-no-wrap">
                        <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                            <th class="px-3 py-2">Username</th>
                            <th class="px-3 py-2">Account Expired</th>
                            <th class="px-3 py-2">Account Locked</th>
                            <th class="px-3 py-2">Password Expired</th>
                            <th class="px-3 py-2">Enabled</th>
                            <th class="px-3 py-2">Edit</th>
                            <th class="px-3 py-2">Show</th>
                            <th class="px-3 py-2">Delete</th>

                        </tr>
                        <tbody
                                class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800"
                        >
                        <g:each in="${userList}">
                            <tr class="text-gray-700 dark:text-gray-400">
                                <td class="px-3 py-2">${it.username}</td>
                                <td class="px-3 py-2">${it.accountExpired}</td>
                                <td class="px-3 py-2">${it.accountLocked}</td>
                                <td class="px-3 py-2">${it.passwordExpired}</td>
                                <td class="px-3 py-2">${it.enabled}</td>
                                <td class="px-3 py-2"><g:link controller='user' action='edit' id='${it.id}'
                                                                  class="btn btn-success">
                                    <span class="fa fa-pencil"></span></g:link></td>
                                <td class="px-3 py-2"><g:link controller='user' action='show' id='${it.id}'
                                                              class="btn btn-primary"><span class="fa fa-eye"></span></g:link></td>
                                <td class="px-3 py-2">
                                    <g:form resource="${it}" method="DELETE">
                                        <button class="btn btn-danger" type="submit"
                                                onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Êtes-vous sur ?')}');">
                                            <span class="fa fa-trash"></span>
                                        </button>
                                    </g:form>

                                </td>

                            </tr>
                        </g:each>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800 flex col-span-4 mt-2 sm:mt-auto sm:justify-end ">>
                <g:paginate total="${userCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/user/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
    <div style="margin-top:10px" role="navigation">
        <ul>
            <li><button class="px-3 py-1 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-md active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"><g:link class="" action="index">Back</g:link></button></li>

        </ul>
    </div>
        <div id="show-user" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <div class="h-full pb-16 overflow-y-auto">
                <div class="container px-6 mx-auto grid">
                    <h2
                            class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200"
                    >
                        Here is the detailed User
                    </h2>
                    <!-- CTA -->


                    <!-- Big section cards -->
                    <h4
                            class="mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300"
                    >
                        Information
                    </h4>
                    <div
                            class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800"
                    >
                        <p class="text-sm text-gray-600 dark:text-gray-400">
                            Username : ${user.username}
                        </p>

                    </div>
                    <div
                            class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800"
                    >
                        <p class="text-sm text-gray-600 dark:text-gray-400">
                            password : ?????????
                        </p>

                    </div>

                    <!-- Responsive cards -->
                    <h4
                            class="mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300"
                    >
                        Cared details
                    </h4>
                    <div class="grid gap-6 mb-8 md:grid-cols-2 xl:grid-cols-4">
                        <!-- Card -->
                        <div
                                class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
                        >
                            <div
                                    class="p-3 mr-4 text-orange-500 bg-orange-100 rounded-full dark:text-orange-100 dark:bg-orange-500"
                            >
                                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                    <path
                                            d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z"
                                    ></path>
                                </svg>
                            </div>
                            <div>
                                <p
                                        class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400"
                                >
                                    Account locked ?
                                </p>
                                <p
                                        class="text-lg font-semibold text-gray-700 dark:text-gray-200"
                                >
                                    ${user.accountLocked}
                                </p>
                            </div>
                        </div>
                        <!-- Card -->
                        <div
                                class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
                        >
                            <div
                                    class="p-3 mr-4 text-green-500 bg-green-100 rounded-full dark:text-green-100 dark:bg-green-500"
                            >
                                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                    <path
                                            fill-rule="evenodd"
                                            d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z"
                                            clip-rule="evenodd"
                                    ></path>
                                </svg>
                            </div>
                            <div>
                                <p
                                        class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400"
                                >
                                    Password exprired
                                </p>
                                <p
                                        class="text-lg font-semibold text-gray-700 dark:text-gray-200"
                                >
                                    ${user.passwordExpired}
                                </p>
                            </div>
                        </div>
                        <!-- Card -->
                        <div
                                class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
                        >
                            <div
                                    class="p-3 mr-4 text-blue-500 bg-blue-100 rounded-full dark:text-blue-100 dark:bg-blue-500"
                            >
                                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                    <path
                                            d="M3 1a1 1 0 000 2h1.22l.305 1.222a.997.997 0 00.01.042l1.358 5.43-.893.892C3.74 11.846 4.632 14 6.414 14H15a1 1 0 000-2H6.414l1-1H14a1 1 0 00.894-.553l3-6A1 1 0 0017 3H6.28l-.31-1.243A1 1 0 005 1H3zM16 16.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zM6.5 18a1.5 1.5 0 100-3 1.5 1.5 0 000 3z"
                                    ></path>
                                </svg>
                            </div>
                            <div>
                                <p
                                        class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400"
                                >
                                    Enabled
                                </p>
                                <p
                                        class="text-lg font-semibold text-gray-700 dark:text-gray-200"
                                >
                                    ${user.enabled}
                                </p>
                            </div>
                        </div>
                        <!-- Card -->
                        <div
                                class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
                        >
                            <div
                                    class="p-3 mr-4 text-teal-500 bg-teal-100 rounded-full dark:text-teal-100 dark:bg-teal-500"
                            >
                                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                    <path
                                            fill-rule="evenodd"
                                            d="M18 5v8a2 2 0 01-2 2h-5l-5 4v-4H4a2 2 0 01-2-2V5a2 2 0 012-2h12a2 2 0 012 2zM7 8H5v2h2V8zm2 0h2v2H9V8zm6 0h-2v2h2V8z"
                                            clip-rule="evenodd"
                                    ></path>
                                </svg>
                            </div>
                            <div>
                                <p
                                        class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400"
                                >
                                   Account expired
                                </p>
                                <p
                                        class="text-lg font-semibold text-gray-700 dark:text-gray-200"
                                >
                                    ${user.accountExpired}
                                </p>
                            </div>
                        </div>
                    </div>

                    <!-- Cards with title -->


                    <div class="grid gap-6 mb-8 md:grid-cols-2">
                        <g:form resource="${this.user}" action="edit">
                            <div class="">
                                <g:link  action="edit" resource="${this.user}"><button class="px-10 py-4 font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" >Edit</button></g:link>
                            </div>
                        </g:form>
                        <g:form resource="${this.user}" method="DELETE">
                            <g:if test="${(user.id).toString().equals(sec.loggedInUserInfo(field: 'id').toString())}">
                                <div class="">
                                    <button class="px-10 py-4 font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg opacity-50 cursor-not-allowed focus:outline-none"  type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}"  >Delete</button>
                                </div>
                            </g:if>
                            <g:else>
                                <div class="">
                                    <button  class="px-10 py-4 font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" >Delete</button>
                                </div>
                            </g:else>


                        </g:form>
                    </div>
            </div>
            </main>
        </div>
    </body>
</html>